config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "equipment/:id/count_status", to: "equipment#count_status"

  resources :equipment, only: [:index, :show, :create, :update] do
    resources :bookings, only: [:new, :create, :edit, :update]
    resources :reviews, only: [ :new, :create ]
  end

  resources :bookings, only: [:show, :index, :update]

  get "/my_equipment", to: "equipment#my_equipment"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  STATUS = %w[pending confirmed cancelled returned]
  belongs_to :equipment
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :start_date, :end_date, overlap: { scope: "equipment_id" }
  validates :status, inclusion: { in: STATUS }, presence: true
  validate :end_date_valid?
  validate :start_date_valid?, on: :create

  def start_date_valid?
    past = start_date.strftime("%m/%d/%Y") < Time.now.strftime("%m/%d/%Y")
    errors.add(:start_date, "Can't be set before today") if past
  end

  def end_date_valid?
    errors.add(:end_date, "Can't be set before start date") if end_date < start_date
  end
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  CATEGORY = %w[brass guitar keyboard percussion strings woodwind equipment turntable]
  belongs_to :user
  has_many :bookings
  has_many :reviews, dependent: :destroy
  validates :ad_name, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORY }
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  has_many_attached :photos

  include PgSearch::Model
  pg_search_scope :search_equipment,
    against: %i[category description ad_name],
  using: {
    tsearch: { prefix: true }
  }

  def status_check?
    unless self.bookings.nil?
      self.bookings.each do |booking|
        return %w[pending confirmed].include?(booking.status.downcase)
      end
    end
    false
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :equipment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :equipments
  has_many :bookings
  has_many :bookings_as_renter, through: :equipments, source: :bookings
  validates :name, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:update]

  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
    @review = Review.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.equipment = Equipment.find(params[:equipment_id])
    @booking.user = current_user
    @booking.status = "pending"
    @equipment = @booking.equipment
    authorize @equipment
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render 'equipment/show'
    end
  end

  def update
    @booking.update(status: params[:status])
    if @booking.equipment.user == current_user
      redirect_to equipment_path(@booking.equipment)
    else
      @bookings = Booking.all
      authorize @bookings
      redirect_to bookings_path
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:equipment_id, :user_id, :start_date, :end_date, :status)
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :set_equipment, only: %i[show update count_status]

  def index
    @equipments = policy_scope(Equipment)
    if params[:search].present?
      query = params[:search][:query]
      category = params[:search][:category]
      if query.present? && category.present?
        @equipments = policy_scope(Equipment).search_equipment(query).search_equipment(category)
      elsif query.present?
        @equipments = policy_scope(Equipment).search_equipment(query)
      elsif category.present?
        @equipments = policy_scope(Equipment).search_equipment(category)
      end
    end
  end

  def my_equipment
    @equipments = Equipment.where(user: current_user).order(created_at: :desc)
    authorize @equipments
    @equipment = Equipment.new
    authorize @equipment
  end

  def create
    @equipment = Equipment.new(equipment_params)
    @equipment.user = current_user
    authorize @equipment
    if @equipment.save
      redirect_to :my_equipment
    else
      @equipments = Equipment.where(user: current_user)
      authorize @equipments
      render :my_equipment
    end
  end

  def show
    @booking = Booking.new
    authorize @booking
    authorize @equipment
    @marker = [{ lat: @equipment.user.latitude, lng: @equipment.user.longitude }]
  end

  def update
    @equipment.update(active: params[:active])
    authorize @equipment
    redirect_to my_equipment_path(anchor: "equipment-#{@equipment.id}")
  end

  def count_status
    respond_to do |format|
      format.html
      format.json do
        render json: {
          pending_equipment: @equipment.bookings.where(status: 'pending'),
          confirmed_equipment: @equipment.bookings.where(status: 'confirmed')
        }
      end
    end
  end

  private

  def equipment_params
    params.require(:equipment).permit(:category, :ad_name, :description, :price, :active, :search, photos: [])
  end

  def set_equipment
    @equipment = Equipment.find(params[:id])
    authorize @equipment
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_equipment

  # def new
  # end

  def create
    @review = Review.new(review_params)
    @review.equipment = @equipment
    authorize @review
    if @review.save
      redirect_to equipment_path(@equipment)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

  def set_equipment
    @equipment = Equipment.find(params[:equipment_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <div class="flick-title banner">
    <div class="row">
      <div class="col-10 offset-1 col-lg-8 offset-lg-2 my-3">
        <h2 class='m-5'>Bookings</h2>
      </div>
    </div>
  </div>
  <div class="row">
    <% @bookings.select { |booking| booking.user == current_user }.sort_by{ |booking| booking.start_date }.each do |booking| %>
      <div class="col-6">
        <div class="card-product">
          <% unless booking.equipment.photos.attached? %>
            <%= cl_image_tag('nd6mdgkmkyp5fok5ig9n.png', crop: :fill) %>
          <% else %>
            <%= cl_image_tag(booking.equipment.photos.first.key, crop: :fill) %>
          <% end %>
          <div class="card-product-infos">
            <%= link_to equipment_path(booking.equipment), class: 'no-decoration' do %>
              <h2><%= booking.equipment.ad_name %></h2>
              <p><%= booking.equipment.category.capitalize %> owned by <%= booking.equipment.user.name.capitalize %></p>
              <p><%= l(booking.start_date.to_date, format: :long) %> to <%= l(booking.end_date.to_date, format: :long) %></p>
              <p><%= ActiveSupport::NumberHelper.number_to_currency((booking.equipment.price * (booking.end_date.to_date - booking.start_date.to_date + 1)).round, locale: :ja) %></p>
            <% end %>
            <div class="row mt-3">
              <h2 class='mx-3 status-colorize'><%= booking.status.capitalize %></h2>
              <% if booking.status == "returned" %>
                <button type="button" class="btn btn-outline-warning btn-md mx-3" data-toggle="modal" data-target="#exampleModalCenter">
                  Review
                </button>
                <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">My review</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <%= simple_form_for [ booking.equipment, @review ] do |f| %>
                          <%= f.input :content, label: false %>
                          <%= f.submit "Submit review", class: "btn btn-outline-warning btn-md" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              <% elsif booking.start_date > Time.now && booking.status != 'cancelled' %>
                <%= simple_form_for booking, method: 'patch' do |f| %>
                  <button type="submit" class='btn btn-outline-warning btn-md mx-3' value='cancelled' name='status'>Cancel</button>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<%= simple_form_for [@equipment, @booking] do |f| %>
  <%= f.input :start_date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, html5: true %>
  <%= f.submit "Confirm booking", class: "btn btn-primary" %>
<% end %>

app/views/equipment/index.html.erb
<div class="container">
  <div class="flick-title banner">
    <div class="row">
      <div class="col-10 offset-1 col-lg-8 offset-lg-2 my-3">
        <h2 class='m-5'>Equipment</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-8 offset-2 col-lg-6 offset-lg-3 my-3">
        <%= simple_form_for :search, url: equipment_index_path, method: :get, wrapper: :input_group do |f| %>
          <%= f.input :query,
                label: false,
                prepend: 'Search for',
                wrapper_html: {class: 'my-1'} %>
          <%= f.input :category,
                collection: Equipment::CATEGORY,
                label: false,
                prepend: 'Category',
                wrapper_html: {class: 'my-1'} %>
          <button type="submit" class='btn btn-outline-light btn-md'><%= icon('fas','search') %> Search</button>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row pt-3">
    <% @equipments.each do |equipment| %>
      <% if equipment.active && equipment.user != current_user %>
        <%= link_to equipment_path(equipment), class: 'col-12 col-md-6 col-lg-4 my-3 no-decoration' do %>
          <div class="card-trip h-100">
            <% unless equipment.photos.attached? %>
              <%= cl_image_tag('nd6mdgkmkyp5fok5ig9n.png', crop: :fill) %>
            <% else %>
              <%= cl_image_tag(equipment.photos.first.key, crop: :fill) %>
            <% end %>
            <div class="card-trip-infos">
              <div>
                <h2><%= equipment.ad_name %></h2>
                <p><%= equipment.category.capitalize %></p>
              </div>
              <h2 class="card-trip-pricing"><%= ActiveSupport::NumberHelper.number_to_currency(equipment.price, locale: :ja) %> / day</h2>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/equipment/my_equipment.html.erb
<div class="container">
  <div class="flick-title banner">
    <div class="row">
      <div class="col-10 offset-1 col-lg-8 offset-lg-2 my-3">
        <h2 class='m-5'><%= current_user.name.capitalize %>'s Equipment</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-10 offset-1 col-lg-8 offset-lg-2 my-3">
        <%= simple_form_for @equipment, remote: true, wrapper: :input_group do |f| %>
          <%= f.input :category,
                collection: Equipment::CATEGORY,
                label: false,
                prepend: 'Category',
                wrapper_html: {class: 'my-1'} %>
          <%= f.input :ad_name,
                label: false,
                prepend: 'Name',
                wrapper_html: {class: 'my-1'} %>
          <%= f.input :description,
                label: false,
                prepend: 'Description',
                wrapper_html: {class: 'my-1'} %>
          <%= f.input :price,
                label: false,
                prepend: 'Rent price',
                append: '¥ / day',
                wrapper_html: {class: 'my-1'} %>
          <%= f.input :photos,
                as: :file,
                label: false,
                input_html: { multiple: true } %>
          <%= f.input :active,
                wrapper: :custom_boolean_switch,
                label: 'Check to Start Renting Now' %>
          <%= f.submit 'Add', class: 'btn btn-outline-light btn-md' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row pt-3">
    <% @equipments.select { |equipment| equipment.user == current_user }.each do |equipment| %>
      <div class="col-12 col-lg-6">
        <div class='card-product <%= 'opacity-3' unless equipment.active? %>' id="equipment-<%= equipment.id %>" data-controller="counter" data-counter-id=<%= equipment.id %>>
          <% unless equipment.photos.attached? %>
            <%= cl_image_tag('nd6mdgkmkyp5fok5ig9n.png', crop: :fill) %>
          <% else %>
            <%= cl_image_tag(equipment.photos.first.key, crop: :fill) %>
          <% end %>
          <div>
            <%= link_to equipment_path(equipment), class: 'no-decoration' do %>
              <div class="card-product-infos">
                <h2><%= equipment.ad_name %> </h2>
                <p><%= equipment.category.capitalize %> owned by <%= equipment.user.name.capitalize %></p>
                <p><%= ActiveSupport::NumberHelper.number_to_currency(equipment.price.round, locale: :ja) %>/day</p>
              </div>
            <% end %>
            <div class="m-3">
              <%= simple_form_for equipment, remote: true, method: 'patch' do |f| %>
                <% if equipment.active? %>
                  <button <%= 'disabled' if equipment.status_check? %> type="submit" class='btn btn-outline-danger btn-md mx-3 my-1' value='<%= false %>' name='active'>Deactivate</button>
                <% else %>
                  <button type="submit" class='btn btn-outline-success btn-md mx-3 my-1' value='<%= true %>' name='active'>Activate</button>
                <% end %>
              <% end %>
            </div>
            <div class="m-1 ml-4">
              <button type="button" class="btn btn-success" disabled>Comfirmed
                <span class="badge badge-light" data-counter-target="countConfirmed">0</span>
              </button>
              <button type="button" class="btn btn-warning" disabled>Pending
                <span class="badge badge-light" data-counter-target="countPending">0</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/equipment/show.html.erb
<div class="container">
  <div class="flick-title banner">
    <div class="row">
      <div class="col-10 offset-1 col-lg-8 offset-lg-2 my-3">
        <h2 class='m-5'>Rent</h2>
      </div>
    </div>
  </div>
  <div class="card-header">
    <h1 class="text-center" id=""><%= @equipment.ad_name %> </h1>
  </div>
  <div class="flex-container col-12">
    <div class="card-trip col-8 no-padding">
      <div class="flex-container">
        <div class="flex-container">
          <% if @equipment.photos.attached? && @equipment.photos.count > 1 %>
            <div class="flex-large">
              <%= cl_image_tag(@equipment.photos.first.key, crop: :fill) %>
            </div>
            <div class="flex-small">
              <%= cl_image_tag(@equipment.photos[1].key, crop: :fill) %>
              <% if @equipment.photos.count > 2 %>
                <%= cl_image_tag(@equipment.photos[2].key, crop: :fill) %>
              <% end %>
            </div>
          <% elsif @equipment.photos.count == 1 %>
            <div class="flex-large">
              <%= cl_image_tag(@equipment.photos.first.key, crop: :fill) %>
            </div>
          <% else %>
            <%= cl_image_tag('nd6mdgkmkyp5fok5ig9n.png', crop: :fill) %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="flex-container col-4">
      <div class="flex-map">
        <div id="map"
          style="width: 100%; height: 600px;"
          data-markers="<%= @marker.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
  <% if @equipment.active && @equipment.user != current_user %>
    <div class="flex-container col-12" >
      <div class="flex-info col-8">
        <div class="card-trip my-3 text-center" style="background: white;">
          <ul class="list-group list-group-flush text-center" style="width: 100%;">
            <li class="list-group-item border-0 text-center" id="black"> <%= @equipment.description %></li>
            <li class="list-group-item border-top-0 text-center" id="black"> <%= ActiveSupport::NumberHelper.number_to_currency(@equipment.price, locale: :ja) %></li>
            <li class="list-group-item border-top-0 border-bottom-0 text-center" id="black">Owner: <%= @equipment.user.name %></li>
            <li class="list-group-item border-bottom-0 text-center" id="black">Location: <%= @equipment.user.address %> </li>
          </ul>
        </div>
      </div>
      <div class="flex-form col-sm-4 padding-top: 30px">
        <h2>Rent Now</h2>
        <%= simple_form_for [@equipment, @booking] do |f|  %>
          <%= f.input :start_date,
                      as: :date,
                      label: 'From',
                      html5: true%>
          <%= f.input :end_date,
                      as: :date,
                      label: 'To (include)',
                      html5: true %>
          <%= f.submit "Confirm booking", class: "btn btn-outline-light btn-md my-3" %>
        <% end %>
      </div>
    </div>
  <% elsif @equipment.user == current_user %>
    <div class="flex-form col-12">
      <div class="card-trip my-3 text-center" style="background: white;">
        <ul class="list-group list-group-flush text-center" style="width: 100%;">
          <li class="list-group-item border-0 text-center" id="black"> <%= @equipment.description %></li>
          <li class="list-group-item border-top-0 text-center" id="black"> <%= ActiveSupport::NumberHelper.number_to_currency(@equipment.price, locale: :ja) %></li>
          <li class="list-group-item border-top-0 border-bottom-0 text-center" id="black">Owner: <%= @equipment.user.name %></li>
          <li class="list-group-item border-bottom-0 text-center" id="black">Location: <%= @equipment.user.address %> </li>
        </ul>
      </div>
    </div>
    <div class="container text-center">
      <h2>Bookings</h2>
    </div>
    <div class="flex-form col-12 padding-top: 30px">
      <ul class="list-group list-group-flush text-center">
        <% @equipment.bookings.each do |booking| %>
          <li class="list-group-item">
            <div class="row justify-content-between align-items-center">
              <h3 class='text-dark font-weight-bold'><%= booking.user.name %></h3>
              <h3 class='text-dark'>From <%= l(booking.start_date.to_date, format: :long) %></h3>
              <h3 class='text-dark'>To <%= l(booking.end_date.to_date, format: :long) %></h3>
              <h3 class='text-dark'>
                <%= ActiveSupport::NumberHelper.number_to_currency((booking.equipment.price * (booking.end_date.to_date - booking.start_date.to_date + 1)).round, locale: :ja) %>
              </h3>
              <h3 class='status'>
                <%= booking.status.capitalize %>
              </h3>
              <div>
                <%= simple_form_for booking, method: 'patch' do |f| %>
                  <% if booking.status == 'pending' %>
                    <button type="submit" class='btn btn-outline-success btn-md mx-3 my-1' value='confirmed' name='status'>Accept</button>
                    <button type="submit" class='btn btn-outline-warning btn-md mx-3 my-1' value='cancelled' name='status'>Cancel</button>
                  <% elsif booking.status == 'confirmed' %>
                    <button type="submit" class='btn btn-outline-info btn-md mx-3 my-1' value='returned' name='status'>Returned</button>
                  <% end %>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container text-center">
    <h2>Reviews</h2>
    <ul class="list-group list-group-flush text-center" style="width: 100%;">
      <% @equipment.reviews.each do |review| %>
        <li class="list-group-item border-bottom-0 text-center" id="black"><%= review.content %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Soundmate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <% unless current_page?(root_path) || current_page?(new_user_registration_path) || current_page?(new_user_session_path) %>
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
    <% end %>
    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="container home-title flick-title">
  <div class="row py-5">
    <h1 class="col-12 col-lg-7"> SoundMate </h1>
  </div>
  <div class="text-center py-5">
    <% if user_signed_in? %>
      <%= link_to 'Check out all equipment nearby', equipment_index_path, class: "btn btn-outline-light btn-lg" %>
    <% else %>
      <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-outline-light btn-lg" %>
      <%= link_to 'Log in', new_user_session_path, class: "btn btn-outline-light btn-lg" %>
    <% end %>
  </div>
</div>
<div class="text-center py-5 home-font-size" >
  <p>Book instruments and audio equipment from people near you</p>
</div>
<div class="home-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/deumrs4dd/image/upload/v1611836628/pexels-stephen-niemeier-63703_apntj4.jpg)"></div>
<div class="text-center py-5 home-font-size" >
  <p>Rent instruments you don't use</p>
</div>
<div class="home-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/deumrs4dd/image/upload/v1611836711/pexels-photo-65718_g7scnj.jpg)"></div>
<div class="text-center py-5 home-font-size" >
  <p>Discover like minded sound mates with <%= link_to 'SOUNDMATE', new_user_session_path, class: "btn btn-outline-light " %></p>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for [ @equipment, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    SOUNDMATE
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "All equipment", equipment_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1523933095/viqfqp0tfkmcwmj7cfwe.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to my_equipment_path, class: "dropdown-item" do %>
              <% if current_user.equipments %>
                My equipment
              <% else %>
                Add equipment
              <% end %>
            <% end %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>